### ISSUE TITLE
Unit tests are visible in the project

### ISSUE THREAD

**Issue by vvrvvd** [tertle/com.bovinelabs.core#1]
Even though the package was imported through scoped registery the tests are still showing up in testing window which shouldn't happen. My assumption is that the assembly definition for BovineLabs.Core.Tests is missing UNITY_INCLUDE_TESTS define.

**Comment by tertle** [comment]
This definitely shouldn't happen. I'll take a look thanks.

**Comment by tertle** [comment]
This should hopefully be fixed on the 0.15.6 branch (https://gitlab.com/tertle/com.bovinelabs.core/-/tree/0.15.6) and will be pushed to upm/github next release.

**Comment by vvrvvd** [comment]
It does work on the mentioned branch. Thanks! :)
