### ISSUE TITLE
Object Management only works in Unity6 

### ISSUE THREAD

**Issue by aclassen** [tertle/com.bovinelabs.core#5]
Just wanna mention Object Management does not work in Unity2022.3 starting with version 1.2.13 as 'StableTypeHashAttribute'  is only available to Unity6

**Comment by tertle** [comment]
This is correct. All extensions are only tested on Unity 6+ and I only maintain most of the base library for 2022.3 
There are too many UITK changes in Unity 6 for me to maintain anything that has UI

**Comment by aclassen** [comment]
OK thanks for the answer
